## Introduction to Python for Biological and Neuroscientific Applications


## Workshop 1


Python is a versatile, high-level programming language widely favored by scientists and researchers for its readability and flexibility. It finds extensive use across various domains such as computational biology, neuroscience, and biomedical research.
It finds extensive use in tasks ranging from data analysis in genetics to simulating neural networks.

In this section, we'll introduce Python syntax, statements, operators, basic data types, and data structures, focusing on examples relevant to biological and neuroscientific contexts.


### Python Syntax and Statements


Syntax in Python refers to the set of rules governing code structure:

Line Structure: Python programs are organized into logical lines. Blank lines are ignored, and each logical line represents an actionable instruction.

Comments: Denoted by the '#' symbol, comments provide explanatory notes within code.

Indentation: Python uses consistent indentation (typically 4 spaces) to denote nested code blocks.



### Important Note: In Python notation the first element of every structure we will encounter is 0 not 1. So, eg number 2 denotes the 3rd element of an array!!!


### Python Variables



In Python, variables act as containers for data. They are dynamically typed, meaning their type is inferred at runtime.


In [2]:
# Example of assignment statement
a = 10
a += 5  # Increment a by 5
print(a)  # Output: 15


15


In [2]:
# Example of assignment statement
num = 1000
num += 500 # this line of code is equivalent to: num=num+500
num


1500

### Python Operators


Python supports various operators for performing operations on data:

Assignment Operators: Used to assign values to variables.

Arithmetic Operators: Include addition, subtraction, multiplication, division, modulus, and exponentiation.

In [4]:
# Example of arithmetic operators
a = 4 
b = 5
c = a + b  # Addition
print(c)  # Output: 20

print(c / 4)  # Division
print(c % 3)  # Modulus
print(c * 2)  # Multiplication
print(c ** 2)  # Exponentiation


9
2.25
18
81


#### Exercise: calculate the sum of item 1 and 2 and display the outcome
item1 = 3.5 
item2 = 2.0




In [ ]:
# Enter your code here: 






## Python Basic Data Types


Python offers several built-in data types:



#### Strings: Represented as sequences of characters within single or double quotes.

In [4]:
hello = 'Hello'
print(hello)  # Output: Hello
print(type(hello))  # Output: <class 'str'>


Hello
<class 'str'>


In [9]:
#  sequence
sequence1 = 'ATCGGTA'
sequence2 = "UACCGUA"

print(sequence2)

UACCGUA


#### Numbers (Integers, Floats, Complex): 



Integers: Whole numbers


Floats: Decimal numbers




In [11]:
# Example of integers and float numbers
a = 3
b = 3.2354

print(type(a))  # Output: <class 'int'>
print(type(b))  # Output: <class 'float'>


<class 'int'>
<class 'float'>


In [12]:
# Example with biological data
population_size = 1000
migration_rate = 0.05



#### Booleans: Represented as True or False, useful for logical operations.


In [212]:
#  booleans and operations
a = True
b = False

print(a and b)  # Output: False
print(a or b)  # Output: True
print(not b)  # Output: True
print (a == b)# Output: False  # do not confuse the logical operator '==' with the assignment operator '=' 
print (a != b) # True
print(a == (not b)) # True

False
True
True
False
True
True


In [1]:
# neuroscientific context

A_spiking = True

B_spiking = False



Let's imagine that a specific behavioural pattern arises only when neuron A is spiking and neuron B is resting.
We can model this relationship with the following line of code:

In [5]:
pattern= A_spiking and B_spiking
print('Does the pattern arise?')
pattern

Does the pattern arise?


False

We can see that the behavioural pattern does not arise. You can adjust the values in A_spiking and B_spiking until it does.

We can also model more complex relationships using logical operators. For example another behavioural pattern might be mediated by 2 neurons when either both of them are spiking or they are both resting.Can you model this relationship usingthe boolean operators 'and' / 'or'?

## Python Data Structures

Python provides various data structures to organize and manipulate data:



#### Lists: Ordered collections of elements, mutable and accessible by index.


In [8]:
# Example of lists
brain_regions = ['frontal lobe', 'occipital lobe', 'hippocampus']

print(brain_regions[0])  # Output: frontal lobe

brain_regions.append('cerebellum')
print(brain_regions)  # Output: ['frontal lobe', 'occipital lobe', 'hippocampus', 'cerebellum']


frontal lobe
['frontal lobe', 'occipital lobe', 'hippocampus', 'cerebellum']


#### Tuples: Similar to lists but immutable once defined.


In [219]:
# Example of tuples
proteins = ('insulin', 'heamoglobin', 'collagen')

print(proteins[1])  # Output: heamoglobin


heamoglobin


In [18]:
# Example with genetic data
gene_info = ('gene 1', 'gen 2 ', 'gene 3')
print(gene_info[0])  # Output: gene 1


gene 1


#### Dictionaries: Unordered collections of key-value pairs, useful for mapping.


In [10]:
# Example of dictionaries
gene_expression = {'gene1': 5.6, 'gene2': 2.3, 'gene3': 7.1}

print(gene_expression['gene2'])  # Output: 2.3


2.3


In [23]:
# Example 
protein_concentration = {'insulin (μU/mL)': 10 , 'heamoglobin (units/mL)': 15 
 , 'collagen': 20}

print(protein_concentration)  
print(protein_concentration['insulin (μU/mL)'])  


{'insulin (μU/mL)': 10, 'heamoglobin (units/mL)': 15, 'collagen': 20}
10


## Python Control Flow


Control flow dictates the order of statement execution based on conditions:



### Conditional Statements: Utilized for decision-making using if, elif, and else clauses.


In [12]:
# Example of conditional statements
temperature = 25

if temperature > 30:
    print("It's hot!")
elif temperature > 20:
    print("It's warm.")
else:
    print("It's cool.")


It's warm.


In [35]:
# Example with biological conditions
expression_level = 500

if expression_level > 100:
    print("High gene expression")
else:
    print("Low gene expression")


High gene expression


### Loops (For and While): Iterative constructs to execute code repeatedly.


In [14]:
# Example of loops
brain_regions = ['frontal lobe', 'occipital lobe', 'hippocampus']

# For loop
for region in brain_regions:
    print(region)




frontal lobe
occipital lobe
hippocampus


### Exercise 1. For Loop Exercise

Task: Write a program that prints the square of numbers from 1 to 10 using a for loop.


Instructions 


Use a for loop to iterate through numbers from 1 to 10.
Inside the loop, calculate the square of the current number.
Print the number and its square in the format: Number: X, Square: Y.

In [ ]:
#Enter your code here: 




### Exercise 2: If Statements (and for loops)

Task: Write a program that checks if numbers from 1 to 20 are even or odd.


Instructions:


Use a for loop to iterate through numbers from 1 to 20.
Inside the loop, use an if statement to check if the number is even (divisible by 2).
Print "Even" if the number is even and "Odd" otherwise.

In [ ]:
#Enter your code here: 






### Exercise 3. Calculate the Mean


Task: Write a program to calculate the mean of a given dataset.


Instructions:

Use the following dataset: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50].
Calculate the mean by summing all numbers in the dataset and dividing by the total count of numbers.
Print the result as: The mean is: X.

In [ ]:
#Enter your code here: 




## Python Functions and Modules


Functions encapsulate reusable code:



#### Built-in and Custom Functions: Python includes built-in functions and allows users to define custom functions.


### Built-in Functions
Python includes many built-in functions like len(), type(), etc.

With the added information that the function sum() adds the elements of an array:

Eg

In [9]:
sum([3,4,5])

12

And the function len gives the number of the elements of an array:

In [10]:
len([3,4,5])

3

How would you adapt the code you wrote for Exercise 3?

In [ ]:
#Enter your code here: 






### Custom Functions
Users can define custom functions tailored to specific tasks.

There is another way to calculate the mean:

In [16]:
# Example of a custom function
def calculate_mean(data):
    """
    Calculate mean of a list of numbers.
    """
    mean = sum(data) / len(data)
    return mean

numbers = [1, 2, 3, 4, 5]
print(calculate_mean(numbers))  # Output: 3.0


3.0


##### Or, as we will see in the next section, we can calculate the mean using the np.mean function...
    

In [36]:
# Example with biological data
def calculate_gc_content(sequence):
    gc_count = sequence.count('G') + sequence.count('C')
    total_bases = len(sequence)
    return gc_count / total_bases

dna_sequence = 'ATGCGATCGATCGTAGCTAGCTGATCG'
gc_content = calculate_gc_content(dna_sequence)
gc_content


0.5185185185185185

In [38]:
# Example with neuroscience
def calculate_membrane_potential(current, resistance):
    """
    Calculates membrane potential based on Ohm's law.
    """
    return current * resistance

voltage = calculate_membrane_potential(5.0, 10.0)
voltage


50.0

## Modules and libraries: 
Collections of functions and classes that extend Python's capabilities.


Python includes many different libraries, like numpy, math, matplotlib etc


Using the "import" command, you can call these libraries and use their built-in functions

### We will now introduce some of the most useful Python libraries for data analysis and visualisation


## Introduction to NumPy for Array Creation and Manipulation


## NumPy Introduction


NumPy is a fundamental package for numerical computing in Python, essential for tasks involving arrays, matrices, and linear algebra, critical in biological simulations and data analysis.



### Vector Definition


NumPy arrays are used to represent vectors, crucial in representing genetic sequences or neural activations.



In [150]:
import numpy as np

# Create a 1D NumPy array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1d)

# Create a 2D NumPy array (matrix)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr2d)


1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]


### Exercise 4. 

Using numpy, create a 1D array of hear rates during exercise: 

Use these values: 120, 125, 115, 110, 130

In [158]:
# 






Heart Rates (bpm):
[120 125 115 110 130]


### Basic Array Operations

In [30]:
import numpy as np

# Create NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise operations
print("Element-wise addition:")
print(arr1 + arr2)

print("\nElement-wise multiplication:")
print(arr1 * arr2)




Element-wise addition:
[5 7 9]

Element-wise multiplication:
[ 4 10 18]


Example:

In [31]:
import numpy as np

# Create NumPy arrays for analysis of neural firing rates
neural_activity_trial1 = np.array([20, 25, 30, 35, 40])
neural_activity_trial2 = np.array([18, 22, 28, 33, 38])

# Element-wise operations: Calculate difference in firing rates
difference = neural_activity_trial2 - neural_activity_trial1
print("Difference in Firing Rates (Trial 2 - Trial 1):")
print(difference)



Difference in Firing Rates (Trial 2 - Trial 1):
[-2 -3 -2 -2 -2]


### Creating Arrays with NumPy Functions

In [153]:
import numpy as np

# Create arrays using NumPy functions
zeros_array = np.zeros((2, 3))  # 2x3 array of zeros
ones_array = np.ones((3, 4))    # 3x4 array of ones
random_array = np.random.rand(3, 2)  # 3x2 array of random numbers in [0, 1)

print("Zeros Array:")
print(zeros_array)

print("\nOnes Array:")
print(ones_array)

print("\nRandom Array:")
print(random_array)


Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Random Array:
[[0.62889844 0.39843426]
 [0.06271295 0.42403225]
 [0.25868407 0.84903831]]


These functions are very useful in simulating data:

In [168]:
import numpy as np

# Create arrays using NumPy functions for muscle strength data
strength_gains_week1 = np.random.rand(7) * 2  # 1D   gains over week 1(kgs)
strength_gains_week2 = np.random.rand(7) * 5     # week 2

# Generate random array for muscle strength progress (kgs)
muscle_strength_progress = strength_gains_week2-strength_gains_week1
print("Muscle Strength Progress (kgs) for 7 athletes:")
print(muscle_strength_progress)


Muscle Strength Progress (kgs) for 7 athletes:
[ 3.27557018  1.26805061  0.96961961 -0.57732551  1.18345094  1.45892054
  0.05760649]


### Indexing and Slicing


#### In python the first element of a data structure is has the position 0!!! 

Therefore, if you want to access the second elemend you use the index 2, for the 2nd, the index 3 etc

In [4]:
import numpy as np

# Create a 2D NumPy array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indexing
print("Element at (1, 2):", arr2d[0, 1])  # Accessing element in the first row, second column !!!!

# Slicing
print("\nSlicing:")
print("First row:", arr2d[0, :])      # First row (index=0 for the first row!)
print("First column:", arr2d[:, 0])   # First column
print("Subarray from first two rows and last two columns:")
print(arr2d[:2, -2:])


Element at (1, 2): 2

Slicing:
First row: [1 2 3]
First column: [1 4 7]
Subarray from first two rows and last two columns:
[[2 3]
 [5 6]]


How to calculate the mean:

In [6]:
heart_rate=[120,75,60,92,101,83]
meanHR=np.mean(heart_rate)
print(meanHR)

88.5


### One of the advantages of python is its versatility. How many different ways to calculate the mean have we encountered? 